Used 'long' as primary key in `userLibraryService` and refactor the service.
bibliomar/bibliomar-server pull request #6
Opened 2023-03-18 17:44 UTC by mharisraza

Uses 'long' as primary key in 'userLibrary' and refactor the whole service.

2023-03-18 19:41 UTC, mharisraza reviewed
Keep 'user's username' as primary key in userLibrary

2023-03-18 22:43 UTC, Lamarcke commented on src/main/java/bibliomar/bibliomarserver/repositories/UserLibraryRepository.java
This one looks fine, but you may want to use CrudRepository instead to keep consistency with the other repos (though it doesn't make difference.)

2023-03-18 22:57 UTC, Lamarcke requested changes
Great work as always.

I've added some reviews to some bits that need to be changed, please pay close attention to the sendRecoveryEmail method.

2023-03-18 22:57 UTC, Lamarcke commented on src/main/java/bibliomar/bibliomarserver/services/UserLibraryService.java
Some methods here refer to a UserLibrary ID that shouldn't exist anymore. Please update them to use username instead.

2023-03-18 22:57 UTC, Lamarcke commented on src/main/java/bibliomar/bibliomarserver/services/impl/UserLibraryServiceImpl.java
Please update all methods that use "findById" to use "findByUsername" instead.

Also, since you are receiving a String as first argument from the controller, this code shouldn't work.

2023-03-18 22:57 UTC, Lamarcke commented on src/main/java/bibliomar/bibliomarserver/services/impl/UserServiceImpl.java
This is the most important one. 

This method **should** keep using a JWT token, because it grants temporary access to the _/user/update_ endpoint (this token is used by the front-end to update a user's password).

JWT tokens can be signed, and are harder to fabricate. It can be a good idea to reduce the expire time for the PasswordlessToken (genereted by this method) to something like 1h or so.

As a rule of thumb, always prefer to use JWTs when giving access to protected user data.

2023-03-19 14:29 UTC, Lamarcke approved these changes

2023-03-19 14:30 UTC, Lamarcke commented
lgtm

2023-03-19 14:30 UTC, merged